In [1]:
print(2+2)

4

In [2]:
s = [1,2,3,"hola", 7+3]

5-element Vector{Any}:
  1
  2
  3
   "hola"
 10

In [8]:
s, s[1], s[2], s[end]

(Any[1, 2, 3, "hola", 10], 1, 2, 10)

In [15]:
v = [1, 2, 3]
w = [1.2, 7, pi]
v, w, v + w

([1, 2, 3], [1.2, 7.0, 3.141592653589793], [2.2, 9.0, 6.141592653589793])

In [ ]:
v .* w # hadamard

3-element Vector{Float64}:
  1.2
 14.0
  9.42477796076938

In [50]:
for i in 0:1
    println(i)
end


0
1


## Matrices

In [ ]:
A = [3 2 2; -1 1 1; -2 2 4]
B = [1 0 0; 0 1 0; 0 0 1]
C = [0 1 -1; 5 -2 1]
D = randn(78,78)
I = ones(3,3)
Z = inv(D) #0.0s 'O', deberia medir en μs? (PUEDO ESCRIBIR MU!!! AINT NO WAY USA UNICODE)

78×78 Matrix{Float64}:
  0.113652    -0.159101   -0.022697   …   0.161969    0.034591
  0.125692    -0.176029   -0.121028       0.105554    0.0862171
  0.253989    -0.130591   -0.299135       0.0734311   0.117479
  0.322642    -0.306124   -0.220413       0.248159    0.131298
  0.155035    -0.239046   -0.0220505      0.16671     0.00251898
  0.138966    -0.143584   -0.0977384  …   0.0154169  -0.023631
 -0.030623     0.0037312   0.0538557     -0.0348386   0.0055793
 -0.301274     0.0638133   0.186897      -0.0712435  -0.0773
  0.204614    -0.127641   -0.0171268      0.133663    0.0717586
  0.226071    -0.0299585  -0.220032      -0.0487599   0.0662939
  ⋮                                   ⋱              
  0.0331879   -0.0705934   0.0441355      0.0638615   0.025793
 -0.00734966   0.0376596  -0.0233447  …  -0.0587128  -0.0174565
 -0.125595     0.0994945   0.13759       -0.0695302  -0.0637739
 -0.163289     0.174369    0.135446      -0.112666   -0.0608183
  0.177001     0.175589   -0.07661

In [83]:
a = sqrt(2)
round(a, digits=5)

1.41421

In [86]:
v = [a, a^2, a^0.5, sqrt(a)]

4-element Vector{Float64}:
 1.4142135623730951
 2.0000000000000004
 1.189207115002721
 1.189207115002721

In [118]:
norma2(v) = sqrt(sum(v.^2))
dot(v,w) = sum(v .* w)

dot (generic function with 1 method)

In [ ]:
v = [1 2 3]
w = [4 2 4]
print(norma(v))

3.74165738677394133.162277660168379520

In [121]:
print(norma(v - w))

3.1622776601683795

In [122]:
print(dot(v,w))

20